### PR TITLE
Unify Swift Demos to a Single File

### PR DESCRIPTION
**Pull request by keefertaylor**
## High Level Overview of Change

Work out some build magic in order to use a unified project for the Swift demos.

### Context of Change

There used to be two Xcode projects. Now there is only one. Less confusing to users. 

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Before / After

Easier to understand Swift demo.

## Test Plan

CI

### CODE REVIEW

**Comment by keefertaylor** [comment]
ping @nkramer44

**Comment by nkramer44** [comment]
@keefertaylor woops, missed this.

Please consider splitting this into multiple PRs.  1.5 million lines of code is slightly above my acceptable threshold.

Kidding of course.  Think you checked in the Carthage directory lol. Can you remove that so I can find the actual changes you made?

**Comment by keefertaylor** [comment]
@nkramer44  try now :)

**Comment by amiecorso** [comment]
I accidentally merged this PR https://github.com/xpring-eng/Xpring-SDK-Demo/pull/32 into this branch... so if it's cool with you, the `paymentHistory` Swift demo will ride into master on this horseback?

**Pull request merged**
