### PR TITLE
Refactor Node Demo and Document

### PR DESCRIPTION
**Pull request by keefertaylor**
## High Level Overview of Change

Add README (main and node). 

### Context of Change

Building out demos. 

### Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Before / After
N/A
## Test Plan
CI

### CODE REVIEW

**Comment by hbergren** [comment]
Tagging myself so I remember to look at this later.

**Review by amiecorso — APPROVED** [review]
Looks good to me!

**Review by 0xCLARITY — APPROVED** [review]
LGTM

**Review by 0xCLARITY — APPROVED** [review]
LGTM

**Pull request merged**
